---
- name: Create the namespace postgresql-ha
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: postgresql-ha

- name: postgresql-ha
  community.kubernetes.helm:
    atomic: true
    chart_repo_url: https://charts.bitnami.com/bitnami
    kubeconfig: "{{ kubeconfig_file }}"
    namespace: postgresql-ha
    name: postgresql-ha
    chart_ref: postgresql-ha
    chart_version: 8.6.13
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait_timeout: 10m

