---
- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes

- name: Create the namespace
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ k8s_namespace }}"
        labels: "{{ compute_sre_resource_labels }}"


- name: Install the prometheus operator chart
  community.kubernetes.helm:
    atomic: true
    chart_repo_url: "{{ bitnami_chart_source }}"
    kubeconfig: "{{ kubeconfig_file }}"
    namespace: "{{ k8s_namespace }}"
    name: "{{ prometheus_operator_chart_release_name }}"
    chart_ref: kube-prometheus
    chart_version: "{{ prometheus_operator_chart_version }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait_timeout: 10m
