---
- name: Create the namespace haproxy
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: haproxy

- name: haproxy
  community.kubernetes.helm:
    atomic: haproxy
    chart_repo_url: https://charts.bitnami.com/bitnami
    kubeconfig: "{{ kubeconfig_file }}"
    namespace: haproxy
    name: haproxy
    chart_ref: haproxy
    chart_version: 0.3.14
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait_timeout: 10m

