---
metrics_exporter_ip: "{{ network_control_plane_separated | ternary(service_ip, ansible_host) }}"

# Prometheus chart
prometheus_operator_chart_release_name: cmy-prometheus-operator
prometheus_operator_chart_version: 6.3.0

# Grafana chart
grafana_chart_release_name: cmy-grafana
grafana_chart_version: 6.3.3

# grafana default
grafana:
  enabled: true



alertmanager_mattermost_general: "{{ vault_alertmanager_mattermost_general }}"
alertmanager_mattermost_infra: "{{ vault_alertmanager_mattermost_infra }}"
alertmanager_mattermost_cns: "{{ vault_alertmanager_mattermost_cns }}"
alertmanager_mattermost_sre: "{{ vault_alertmanager_mattermost_sre }}"


#  secrets
grafana_admin_pass: "{{ vault_monitoring_k8s_grafana_admin_pass }}"
