---
- name: Create the namespace harbor
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: harbor

- name: harbor
  community.kubernetes.helm:
    atomic: true
    chart_repo_url: https://charts.bitnami.com/bitnami
    kubeconfig: "{{ kubeconfig_file }}"
    namespace: harbor
    name: harbor
    chart_ref: harbor
    chart_version: 12.3.4
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait_timeout: 10m

