---
- name: Create the namespace monitoring
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

- name: thanos chart
  community.kubernetes.helm:
    atomic: true
    chart_repo_url: https://charts.bitnami.com/bitnami
    kubeconfig: "{{ kubeconfig_file }}"
    namespace: monitoring
    name: thanos
    chart_ref: thanos
    chart_version: 17.9.27
    wait_timeout: 10m
