---

- name: Install Monitoring Components
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true

  roles:
    - role: monitoring/k8s_install_prometheus_operator
      tags:
        - setup_prometheus_operator
  tags:
    - setup_components
