---
- name: Create the namespace external-dns
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: external-dns

- name: external-dns
  community.kubernetes.helm:
    atomic: true
    chart_repo_url: https://charts.bitnami.com/bitnami
    kubeconfig: "{{ kubeconfig_file }}"
    namespace: external-dns
    name: external-dns
    chart_ref: external-dns
    chart_version: 6.2.7
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait_timeout: 10m

