---
- name: Create the namespace nginx-ingress-controller
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: nginx-ingress-controller

- name: nginx-ingress-controller
  community.kubernetes.helm:
    atomic: true
    chart_repo_url: https://charts.bitnami.com/bitnami
    kubeconfig: "{{ kubeconfig_file }}"
    namespace: nginx-ingress-controller
    name: nginx-ingress-controller
    chart_ref: nginx-ingress-controller
    chart_version: 9.1.26
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait_timeout: 10m

